name: notify github trend

on:
  push
  # schedule:
  #   - cron: "0 0 * * *" # 毎日8時間毎に定期実行(時間がutcなので注意)

env:
  QIITA_ACCESS_TOKEN: ${{ secrets.QIITA_ACCESS_TOKEN }}
  QIITA_ARTICLE_ID: ${{ secrets.QIITA_ARTICLE_ID }}
  NOTION_ACCESS_TOKEN: ${{ secrets.NOTION_ACCESS_TOKEN }}
  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout current branch #作業ブランチにchekout
        uses: actions/checkout@v2 #サードパーティの公開アクションを利用
        with:
          ref: ${{ github.ref }}
      - name: Git setting
        run: |
          # pullしておかないと Re-run all jobs 実行時はコケてしまうため
          git pull
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Commit and push
        run: |
          git commit --allow-empty -m "prevent automatic workflow stopping" -m "see: https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow"
          git push
      - name: notion auto post
        run: echo "notion auto post" &&
          sed -e "s|__QIITA_ACCESS_TOKEN__|${QIITA_ACCESS_TOKEN}|g"
          -e "s|__QIITA_ARTICLE_ID__|${QIITA_ARTICLE_ID}|g"
          -e "s|__NOTION_ACCESS_TOKEN__|${NOTION_ACCESS_TOKEN}|g"
          -e "s|__NOTION_DATABASE_ID__|${NOTION_DATABASE_ID}|g" .env.example > .env &&
          docker build -t batch:local . &&
          docker run --rm --env-file=.env batch:local
